Submission of connectorio membership profile.
openhabfoundation/openhabfoundation.github.io pull request #104
Opened 2024-01-18 12:49 UTC by splatch

2024-01-19 21:54 UTC, kaikreuzer requested changes
Thanks for the memberpage. I have some suggestions for improved formulations, see below.

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +ConnectorIO® is service and technology provider focused on openHAB project. We completed number of deployments in Europe - Germany, Switzerland, Liechtenstein and Poland. Our firm is largest publishe
```suggestion
ConnectorIO® is a service and technology provider focused on openHAB project.
We have completed a number of deployments in Europe - Germany, Switzerland, Liechtenstein and Poland.
Our firm is the largest publisher of third party extensions for the openHAB project.
Add-ons which we support integrate a variety of industrial and commercial real estate equipment.
```

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +ConnectorIO's focuses on safety of software and software integration towards production use.
```suggestion
ConnectorIO focuses on safety of software and software integration towards production use.
```

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +Over course of years we developed own [cloud connector](https://connectorio.com/services/cloud/connectorio-cloud/), which works independently of openHAB cloud as well as [energy monitoring solution](
```suggestion
Over the course of years we developed our own [cloud connector](https://connectorio.com/services/cloud/connectorio-cloud/), which works independently of openHAB cloud as well as an [energy monitoring solution](https://connectorio.com/solutions/energy-monitoring/) suited for resource constrained devices.
```

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +We provide failsafe and hassle free upgrade mechanisms thanks to customized software assemblies and embedded linux distribution based on Yocto project.
```suggestion
We provide a failsafe and hassle free upgrade mechanisms thanks to customized software assemblies and an embedded Linux distribution based on Yocto project.
```

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +Our open source integrations work with BACnet, CAN bus, CANopen, OPC UA, Wireless M-Bus, M-Bus as well as PLC equipment manufactured by Beckhoff, Siemens and Fatek using their propertiary protocols.
```suggestion
Our open source integrations work with BACnet, CAN bus, CANopen, OPC UA, Wireless M-Bus, M-Bus as well as with PLC equipment manufactured by Beckhoff, Siemens and Fatek using their proprietary protocols.
```

2024-01-19 21:54 UTC, kaikreuzer commented on members/2024-01-07-connectorio.md
> +**ConnectorIO is registered trademark of Code-House, Łukasz Dywicki**
```suggestion
**ConnectorIO is a registered trademark of Code-House, Łukasz Dywicki**
```

2024-01-23 09:30 UTC, splatch commented
I've committed and squashed all your suggestions, its ready for next review.

2024-01-24 10:44 UTC, kaikreuzer approved these changes
Thanks!

2024-01-24 10:44 UTC, merged